### ISSUE TITLE
Create or modify PST

### ISSUE THREAD

**Issue by kartikeysemwal** [tghanem/pst#2]
Can the library be used to create or modify PST? I don't see functions written for it like AddMessage to some folder or AddAttachment to some message.

**Comment by timothyghanim** [comment]
No, the library does not support creating/writing to PSTs. Always happy if someone has the time to start this effort. Currently, I don't have enough cycles to start this big effort.

**Comment by kartikeysemwal** [comment]
Oh got it. Thanks for clearing this out.
